# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.geosaber.com.br
title: Geosaber - Portal de Geotecnologias
email: geosaber@gmail.com
author: Sidney Goveia
description: > # "Write an awesome description for your new site here. 
  Cursos de QGIS, GRASS GIS, R, PostGIS, FOSS4G
copyright: 'Copyright &copy; 2008 Geosaber. Todos os Direitos Reservados.'
credits: '<a href="http://www.audoc.com.br">Audoc.con Assessoria e Consultoria</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SS_Geosaber
  - title: linkedin
    url: https://linkedin.com/company/geosaber
  - title: facebook
    url: https://facebook.com/pg/geosaber

    
